---

name: typer_template
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.13
  - flake8
  - pytest
  - pytest-cov
  - pytest-mock
  - black
  - mypy
  - yamllint
  - cookiecutter
