---

name: Python CI

on:
  pull_request

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install requierments
      run: |
        pip install -r requirements.txt

    - name: Install Markdownlint
      run: |
        npm install -g markdownlint-cli

    - name: install devcontainer cli
      run: |
        npm install -g @devcontainers/cli

    - name: Install nectos act
      run: |
        cd /
        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
        act --version

    - name: Run markdownlint
      run: |
        markdownlint .

    - name: Run pyinilint
      run: |
        pyinilint mypy.ini

    - name: Run yamllint
      run: |
        yamllint .

    - name: Run black
      run: |
        black ./tests/ --check

    - name: Run flake8
      run: |
        flake8 .

    - name: Run mypy
      run: |
        mypy .

    - name: Run pytest
      run: |
        pytest ./tests --durations=0 --cov -s -v

    - name: Run pre-commit
      run: |
        # This redundant step is just to make sure that the pre-commit hook is working
        ./pre-commit.sh
