---

name: "Debug Action"

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  fork:
  create:
  delete:
  label:
  issues:
  branch_protection_rule:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  issue_comment:
  gollum:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  registry_package:
  release:

jobs:
  event_details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print environment
        uses: hmarr/debug-action@v2.1.0

      - name: pull_request
        if: github.event_name == 'pull_request'
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
          echo "action: ${{ github.event.action }}"
          echo "merged: ${{ github.event.pull_request.merged }}"
          echo "number: ${{ github.event.pull_request.number }}"
          echo "title: ${{ github.event.pull_request.title }}"
          echo "state: ${{ github.event.pull_request.state }}"
          echo "base.ref": ${{ github.event.pull_request.base.ref }}
          echo "head.ref: ${{ github.event.pull_request.head.ref }}"

      - name: push
        if: github.event_name == 'push'
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
          echo "after: ${{ github.event.after }}"
          echo "before: ${{ github.event.before }}"
          echo "base_ref: ${{ github.event.base_ref }}"
          echo "commits.author.name: ${{ github.event.commits.author.name }}"
          echo "compare: ${{ github.event.compare }}"
          echo "created: ${{ github.event.created }}"
          echo "deleted: ${{ github.event.deleted }}"
          echo "description: ${{ github.event.description }}"
          echo "forced: ${{ github.event.forced }}"
          echo "head_commit.author.name: ${{ github.event.head_commit.author.name }}"
          echo "pusher.name: ${{ github.event.pusher.name }}"
          echo "ref: ${{ github.event.ref }}"
          echo "repository.full_name: ${{ github.event.repository.full_name }}"
          echo "sender.login: ${{ github.event.sender.login }}"
      - name: create
        if: github.event_name == 'create'
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#create
          echo "description: ${{ github.event.description }}"
          echo "master_branch: ${{ github.event.master_branch }}"
          echo "pusher_type: ${{ github.event.pusher_type }}"
          echo "ref_type: ${{ github.event.ref_type }}"

      - name: delete
        if: github.event_name == 'delete'
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#delete
          echo "ref: ${{ github.event.ref }}"
          echo "ref_type: ${{ github.event.ref_type }}"
